# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{things-to-basecamp}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Andreas Zecher"]
  s.date = %q{2010-05-18}
  s.default_executable = %q{things-to-basecamp}
  s.description = %q{Export all todos from Things.app in your Inbox, Today or Next focus that are tagged with 'Basecamp:PROJECT_NAME:LIST_NAME' to Basecamp.}
  s.email = %q{updates@pixelate.de}
  s.executables = ["things-to-basecamp"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/things-to-basecamp",
     "lib/basecamp.rb",
     "lib/things-to-basecamp.rb",
     "test/helper.rb",
     "test/test_things-to-basecamp.rb",
     "things-to-basecamp.gemspec"
  ]
  s.homepage = %q{http://github.com/pixelate/things-to-basecamp}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Export todos from Things.app to Basecamp}
  s.test_files = [
    "test/helper.rb",
     "test/test_things-to-basecamp.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

